kind: users
specs:
    -
        username: guy1
        email: guy1@spryker.com
        roles:
            developer:
                - dev
            admin:
                - prod
                - dev-qa-1