kind: environments
specs:
  -
    name: test-prod
    type: prod
    metadata: []
  -
    name: test-dev
    type: dev
    metadata: []
  -
    name: test-qa
    type: dev
    metadata: []
  -
    name: test-qa2
    type: dev-qa-1
    metadata: []
  -
    name: test-qa2
    type: dev-qa-2
    metadata: []